// This file was auto-generated by ML.NET Model Builder. 
using Microsoft.ML;
using Microsoft.ML.Data;
using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
public partial class MLModel
{
    /// <summary>
    /// model input class for MLModel.
    /// </summary>
    #region model input class
    public class ModelInput
    {
        [ColumnName(@"_id")]
        public float __id { get; set; }

        [ColumnName(@"faixa_etaria")]
        public string Faixa_etaria { get; set; }

        [ColumnName(@"idade")]
        public float Idade { get; set; }

        [ColumnName(@"sexo")]
        public string Sexo { get; set; }

        [ColumnName(@"raca_cor")]
        public string Raca_cor { get; set; }

        [ColumnName(@"municipio")]
        public string Municipio { get; set; }

        [ColumnName(@"grupo")]
        public string Grupo { get; set; }

        [ColumnName(@"categoria")]
        public string Categoria { get; set; }

        [ColumnName(@"lote")]
        public string Lote { get; set; }

        [ColumnName(@"vacina_fabricante")]
        public string Vacina_fabricante { get; set; }

        [ColumnName(@"descricao_dose")]
        public float Descricao_dose { get; set; }

        [ColumnName(@"cnes")]
        public string Cnes { get; set; }

        [ColumnName(@"sistema_origem")]
        public string Sistema_origem { get; set; }

        [ColumnName(@"data_vacinacao")]
        public string Data_vacinacao { get; set; }

    }

    #endregion

    /// <summary>
    /// model output class for MLModel.
    /// </summary>
    #region model output class
    public class ModelOutput
    {
        [ColumnName("PredictedLabel")]
        public string Prediction { get; set; }

        public float[] Score { get; set; }
    }

    #endregion

    private static string MLNetModelPath = Path.GetFullPath("MLModel.zip");

    public static readonly Lazy<PredictionEngine<ModelInput, ModelOutput>> PredictEngine = new Lazy<PredictionEngine<ModelInput, ModelOutput>>(() => CreatePredictEngine(), true);

    /// <summary>
    /// Use this method to predict on <see cref="ModelInput"/>.
    /// </summary>
    /// <param name="input">model input.</param>
    /// <returns><seealso cref=" ModelOutput"/></returns>
    public static ModelOutput Predict(ModelInput input)
    {
        var predEngine = PredictEngine.Value;
        return predEngine.Predict(input);
    }

    private static PredictionEngine<ModelInput, ModelOutput> CreatePredictEngine()
    {
        var mlContext = new MLContext();
        ITransformer mlModel = mlContext.Model.Load(MLNetModelPath, out var _);
        return mlContext.Model.CreatePredictionEngine<ModelInput, ModelOutput>(mlModel);
    }
}
